### PR TITLE
Added new method for extracting the page parameter

### PR DESCRIPTION
**Pull request by SGospodinov**
This method can be used to customise the page parameter extraction logic.
e.g. It can use custom page parameter name set by an initializer.

### CODE REVIEW

**Comment by dhh** [comment]
What's the use case you have for this?

**Comment by SGospodinov** [comment]
Currently, the gem use only the `:page` parameter which makes harder to use in already existing apps which are using another param name, for example `:comments_page`.
I think this will make maintenance easier if features like the given will be implemented.

**Comment by dhh** [comment]
What's the difference in changing the existing app to use the page param?
In any case, I'm not keen on adding specialization like that without a
overwhelming case for it. In this case, it's also easy enough just to
overwrite the whole current_param_page method. The logic is minimal.
Appreciate the effort though! Thanks for taking the time to propose.

**Comment by SGospodinov** [comment]
Thank you for the revision

**Pull request closed without merging**
